#!/usr/bin/env bash

TMPDIR=$( mktemp -d 2>/dev/null )
trap 'rm -rf "${TMPDIR}"' EXIT

## Install or Update Homebrew ##
echo 'Installing or Updating Homebrew...'
which -s brew
if [[ $? != 0 ]] ; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    brew update
fi

## Install or Update Ansible ##
echo 'Installing or Updating Ansible...'
which -s ansible-playbook
if [[ $? != 0 ]] ; then
  echo "ansible installation..."
    brew install ansible
fi

## Check out a copy of this repo (first time only) ##
echo 'Checking out macosx-dev-environment repo...'
git clone https://github.com/alexortizrosado/macosx-dev-environment.git ${TMPDIR} 2>/dev/null
pushd ${TMPDIR} && \
  git fetch && \
  git reset --hard origin/master && \
  popd

## Run Ansible Playbook ##
echo 'Handing Playbook to Ansible...'
ansible-playbook ${TMPDIR}/ansible/macosx_environment.yaml -i 127.0.0.1, --verbose
