---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=caskroom/cask

    - name: Install Caskroom
      homebrew: name=brew-cask state=latest

    - name: Install Virtualbox
      homebrew_cask: name=virtualbox state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install Docker Toolbox 
      homebrew_cast: name=dockertoolbox state=latest
 

