---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=caskroom/cask

    - name: Tap Versions
      homebrew_tap: tap=caskroom/versions

    - name: Install Caskroom
      homebrew: name=brew-cask state=latest

    - name: Install Virtualbox
      homebrew_cask: name=virtualbox state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install Docker Toolbox
      homebrew_cask: name=dockertoolbox state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install SublimeText 3
      homebrew_cask: name=sublime-text3 state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install GitHub Desktop
      homebrew_cask: name=github-desktop state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications
